//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Билеты
    {
        public long КодБилета { get; set; }
        public int КодРейса { get; set; }
        public int КодАвиакомпании { get; set; }
        public int КодПассажира { get; set; }
        public string НазваниеКласса { get; set; }
        public System.DateTime ДатаПокупкиБилета { get; set; }
        public System.TimeSpan ВремяПокупкиБилета { get; set; }
        public Nullable<bool> Багаж { get; set; }
    
        public virtual Авиакомпании Авиакомпании { get; set; }
        public virtual Пассажиры Пассажиры { get; set; }
        public virtual Рейсы Рейсы { get; set; }
    }
}
