//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рейсы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Рейсы()
        {
            this.Билеты = new HashSet<Билеты>();
        }
    
        public int КодРейса { get; set; }
        public int КодАвиакомпании { get; set; }
        public int КодСамолёта { get; set; }
        public int Отправление { get; set; }
        public int Прибытие { get; set; }
        public System.DateTime ДатаОтправления { get; set; }
        public System.DateTime ДатаПрибытия { get; set; }
        public System.TimeSpan ВремяОтправления { get; set; }
        public System.TimeSpan ВремяПрибытия { get; set; }
        public string ДлительностьПерелета { get; set; }
        public decimal СтоимостьБилета { get; set; }
    
        public virtual Авиакомпании Авиакомпании { get; set; }
        public virtual Аэропорты Аэропорты { get; set; }
        public virtual Аэропорты Аэропорты1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Билеты> Билеты { get; set; }
        public virtual Самолеты Самолеты { get; set; }
    }
}
