using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Tickets.Ticket
{
    /// <summary>
    /// Логика взаимодействия для ViewForm.xaml
    /// </summary>
    public partial class ViewForm4 : Window
    {
        public ViewForm4()
        {
            InitializeComponent();
        }

        Продажа_билетов_на_самолетEntities db = ContextDB.GetContext();
        private void Find_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (sql1.IsChecked == true)
                {
                    Viewtable.ItemsSource = db.ОпределенныйКласс(ID.Text);
                }
                if (sql2.IsChecked == true)
                {
                    Viewtable.ItemsSource = db.ГородОтправления(ID1.Text);
                }
                if (sql3.IsChecked == true)
                {
                    Viewtable.ItemsSource = db.СтоимостьОпределенногоРейса(Convert.ToInt32(ID2.Text));
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, ex.Source);
            }
        }

        private void Viewtable_AutoGeneratedColumns(object sender, EventArgs e)
        {
            try
            {
                int iHeader = Viewtable.Columns.Where(p => p.Header.ToString() == "ГородОтправления").First().DisplayIndex;
                Viewtable.Columns[iHeader].Header = "Город отправление";
                int iHeader1 = Viewtable.Columns.Where(p => p.Header.ToString() == "НазваниеКласса").First().DisplayIndex;
                Viewtable.Columns[iHeader1].Header = "Название класса";
                int iHeader2 = Viewtable.Columns.Where(p => p.Header.ToString() == "НомерРейса").First().DisplayIndex;
                Viewtable.Columns[iHeader2].Header = "Номер рейса";
                int iHeader3 = Viewtable.Columns.Where(p => p.Header.ToString() == "СтоимостьБилета").First().DisplayIndex;
                Viewtable.Columns[iHeader3].Header = "Стоимость билета";
            }
            catch { }
        }

        private void Сброс_Click(object sender, RoutedEventArgs e)
        {
            ID.Clear();
            ID1.Clear();
            ID2.Clear();
            Viewtable.ItemsSource = null;
        }
    }
}
